In [ ]:
import numpy as np
import pandas as pd

from sqlalchemy import create_engine
from sqlalchemy.types import VARCHAR, Integer, Float

In [316]:
from HTDetect import HTDetect

In [317]:
test = HTDetect(target_vid)

In [318]:
test.main(yaw_threshold=80, dwell_threshold=1.5, HT_break=2, print=True)


 Source ID: Measureyes_0924_01
 Total Persons Detected: 166
 Total HTs Detected: 27
 Total Distinct HTers: 6
 Head-Turn Rate: 0.036
 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 Head xTurn Parameters:
     Yaw Threshold (max allowable face angle left or right of camera): 80 degrees
     Pitch Threshold (max allowable angle up or down from camera): 45 degrees
     Minimum dwell to qualify: 1.5 seconds
     Minimum duration (break) between multiple HTs by single person: 2 seconds
 


In [319]:
test.HTs_df

HT_start  HT_dwell  person_index
1     5797.0     9.384            32
2     6381.0     5.005            33
3     8383.0     2.210            34
4    15765.0     1.627            46
5    17976.0     3.420            34
6    27402.0     6.798            32
7    31990.0     3.211            46
8    37412.0    14.014            32
9    41207.0     3.003            34
10   47005.0     4.796            47
11   54429.0     4.796            46
12   60018.0     5.797            34
13   64022.0     4.421            32
14   73031.0     3.211            46
15   75450.0     1.793            33
16   76034.0     2.002            32
17   82457.0     5.213            32
18   86252.0     9.218            34
19  101267.0     2.211            32
20  104854.0     3.629            34
21  105480.0     1.585            67
22  106648.0     1.835            32
23  110276.0     4.213            33
24  112070.0     4.629            32
25  119285.0     1.794            32
26  121496.0     3.795            47
27  123873.0     4.630            32

In [320]:
test.all_records_df[test.all_records_df['person_index'] == 31]

source_file  timestamp  person_index  \
2037  Measureyes_0924_01_response_0001.json       5588            31   
2038  Measureyes_0924_01_response_0001.json       5630            31   
2039  Measureyes_0924_01_response_0001.json       5714            31   
2040  Measureyes_0924_01_response_0001.json       5797            31   
2041  Measureyes_0924_01_response_0001.json       5839            31   
2042  Measureyes_0924_01_response_0001.json       5922            31   
2043  Measureyes_0924_01_response_0001.json       5964            31   
2044  Measureyes_0924_01_response_0001.json       6047            31   
2045  Measureyes_0924_01_response_0001.json       6131            31   
2046  Measureyes_0924_01_response_0001.json       6172            31   
2047  Measureyes_0924_01_response_0001.json       6256            31   
2048  Measureyes_0924_01_response_0001.json       6297            31   
2049  Measureyes_0924_01_response_0001.json       6381            31   
2050  Measureyes_0924_01_response_0001.json       6506            31   
2051  Measureyes_0924_01_response_0001.json       6589            31   
2052  Measureyes_0924_01_response_0001.json       6631            31   
2053  Measureyes_0924_01_response_0001.json       6715            31   
2054  Measureyes_0924_01_response_0001.json       6923            31   
2055  Measureyes_0924_01_response_0001.json       6965            31   
2056  Measureyes_0924_01_response_0001.json       7048            31   
2057  Measureyes_0924_01_response_0001.json       7132            31   

       face_yaw  face_pitch  face_box_top  face_box_left  
2037        NaN         NaN           NaN            NaN  
2038        NaN         NaN           NaN            NaN  
2039        NaN         NaN           NaN            NaN  
2040        NaN         NaN           NaN            NaN  
2041        NaN         NaN           NaN            NaN  
2042        NaN         NaN           NaN            NaN  
2043        NaN         NaN           NaN            NaN  
2044        NaN         NaN           NaN            NaN  
2045        NaN         NaN           NaN            NaN  
2046 -31.617493   -2.338707      0.372222       0.798437  
2047        NaN         NaN           NaN            NaN  
2048        NaN         NaN           NaN            NaN  
2049        NaN         NaN           NaN            NaN  
2050        NaN         NaN           NaN            NaN  
2051        NaN         NaN           NaN            NaN  
2052        NaN         NaN           NaN            NaN  
2053        NaN         NaN           NaN            NaN  
2054        NaN         NaN           NaN            NaN  
2055        NaN         NaN           NaN            NaN  
2056        NaN         NaN           NaN            NaN  
2057        NaN         NaN           NaN            NaN

In [28]:
connection_str = 'postgresql:///measureyes'
engine = create_engine(connection_str, echo=False)

In [29]:
target_vid = 'Measureyes_0924_01'

Query_raw = ("""
SELECT * 
FROM {}
ORDER BY person_index, timestamp
;""".format(target_vid)
            )

In [30]:
# Import all records for video
all_recs = pd.read_sql_query(Query_raw, engine)

In [249]:
# get the sample rate in milliseconds; it's timestamp at record idx 1
sample_rate = all_recs.loc[1, 'timestamp']
print("sample rate in milliseconds:", sample_rate)

sample rate in milliseconds: 41


In [33]:
# Get dataframe of only records where yaw was recorded
pose_recs = all_recs.dropna(subset=['face_yaw'])

cols = ['timestamp', 'person_index', 'face_yaw', 'face_pitch', 'face_box_top', 'face_box_left']
pose_recs = pose_recs[cols]

In [37]:
pose_recs.head()

timestamp  person_index   face_yaw  face_pitch  face_box_top  \
893       11386            19 -32.426006   -4.658849      0.340278   
2046       6172            31 -31.617493   -2.338707      0.372222   
2058       5797            32  -2.420268    0.076770      0.370833   
2059       6798            32 -14.524308   -2.389813      0.336111   
2061       8383            32 -60.660793  -12.552453      0.323611   

      face_box_left  
893        0.096094  
2046       0.798437  
2058       0.908594  
2059       0.225000  
2061       0.892187

In [55]:
# Filter records further by face pose yaw and pitch thresholds
yaw_threshold = 45 # degrees plus or minus zero facing camera
pitch_threshold = 45

filtered1 = pose_recs.loc[(pose_recs['face_yaw'].abs() <= yaw_threshold) & \
                          (pose_recs['face_pitch'].abs() <= pitch_threshold)]

In [252]:
print(pose_recs['person_index'].unique())
print(len(pose_recs['person_index'].unique()))

[ 19  31  32  33  34  36  37  38  43  46  47  53  57  58  61  62  63  67
  74 112 146 149 153 155 157 165]
26


In [129]:
# Eight most commonly spotted persons with yaws recorded
pd.value_counts(pose_recs['person_index'])

32     153
34     132
33      61
46      57
47      46
67      19
112      4
149      4
58       4
157      4
38       3
36       3
153      2
37       2
155      2
57       2
31       1
165      1
43       1
53       1
61       1
62       1
63       1
74       1
146      1
19       1
Name: person_index, dtype: int64

In [76]:
# Grab and re-index a dataframe of records from only one person_index
df_indiv = pose_recs[pose_recs['person_index'] == 46]
df_indiv.index = range(len(df_indiv))

In [77]:
df_indiv.tail(15)

timestamp  person_index   face_yaw  face_pitch  face_box_top  \
42      73239            46  14.556217   -5.471243      0.227778   
43      73448            46  17.370554    2.666018      0.219444   
44      73656            46  -6.165985    2.091419      0.250000   
45      73823            46 -27.488840   -2.543867      0.250000   
46      74240            46 -32.041859   -2.608912      0.226389   
47      74449            46 -29.948095   -0.328268      0.230556   
48      74616            46 -29.207191   -2.716384      0.229167   
49      74824            46 -22.801897   -6.043785      0.225000   
50      75033            46 -13.164354   -7.152011      0.212500   
51      75241            46  -7.517159   -5.063367      0.226389   
52      75450            46 -16.137062   -4.948359      0.218056   
53      75617            46 -27.744755   -9.258583      0.219444   
54      75825            46 -24.237137  -10.431268      0.243056   
55      76242            46 -53.926182    8.641289      0.266667   
56     123665            46  38.229702   -3.726826      0.233333   

    face_box_left  
42       0.828125  
43       0.730469  
44       0.628125  
45       0.551562  
46       0.412500  
47       0.367969  
48       0.334375  
49       0.292188  
50       0.250781  
51       0.224219  
52       0.210938  
53       0.189063  
54       0.156250  
55       0.014844  
56      -0.004688

In [78]:
# Turn off an annoying and irrelevant SettingWithCopy error: see https://stackoverflow.com/questions/42105859/pandas-map-to-a-new-column-settingwithcopywarning
pd.options.mode.chained_assignment = None

In [79]:
# Make column that shows timedelta from previous row
df_indiv['timediff'] = df_indiv['timestamp'].diff().fillna(0)

In [80]:
cols2 = ['person_index', 'timestamp', 'timediff', 'face_yaw']
df_indiv = df_indiv[cols2]
df_indiv.tail(12)

person_index  timestamp  timediff   face_yaw
45            46      73823     167.0 -27.488840
46            46      74240     417.0 -32.041859
47            46      74449     209.0 -29.948095
48            46      74616     167.0 -29.207191
49            46      74824     208.0 -22.801897
50            46      75033     209.0 -13.164354
51            46      75241     208.0  -7.517159
52            46      75450     209.0 -16.137062
53            46      75617     167.0 -27.744755
54            46      75825     208.0 -24.237137
55            46      76242     417.0 -53.926182
56            46     123665   47423.0  38.229702

In [81]:
# Grab indeces where time deltas indicate a gap between HTs
qq = list(df_indiv[df_indiv['timediff'] == 0].index)
pp = list(df_indiv[df_indiv['timediff'] >= 1500].index)
qq.extend(pp)
ht_starts = np.array(qq)
ht_starts

array([ 0,  7, 23, 41, 56])

In [82]:
# Records at HT starts
df_indiv.loc[ht_starts]

person_index  timestamp  timediff   face_yaw
0             46      15765       0.0   2.307748
7             46      31990   14598.0  54.677425
23            46      54429   19228.0  21.048765
41            46      73031   13806.0  52.025948
56            46     123665   47423.0  38.229702

In [83]:
# Records at HT ends
ht_ends = list(ht_starts[1:] - 1)
ht_ends.append(-1)
ht_ends = np.array(ht_ends)
ht_ends

array([ 6, 22, 40, 55, -1])

In [84]:
df_indiv.iloc[ht_ends, :]

person_index  timestamp  timediff   face_yaw
6             46      17392     417.0  68.354904
22            46      35201     417.0 -63.021053
40            46      59225     208.0  24.894844
55            46      76242     417.0 -53.926182
56            46     123665   47423.0  38.229702

In [85]:
combined = list(ht_starts)
combined.extend(list(ht_ends))
combined.sort()
combined.pop(0)
combined.append(-1)

combined

[6, 7, 22, 23, 40, 41, 55, 56, 56, -1]

In [86]:
# DF showing HT starts and ends
df_indiv.iloc[combined, :]

person_index  timestamp  timediff   face_yaw
6             46      17392     417.0  68.354904
7             46      31990   14598.0  54.677425
22            46      35201     417.0 -63.021053
23            46      54429   19228.0  21.048765
40            46      59225     208.0  24.894844
41            46      73031   13806.0  52.025948
55            46      76242     417.0 -53.926182
56            46     123665   47423.0  38.229702
56            46     123665   47423.0  38.229702
56            46     123665   47423.0  38.229702

In [ ]:
df_indiv.sort_values()

In [268]:
# Calculate a dwell time for a single HT
df_indiv.iloc[-1, 1] - df_indiv.loc[0, 'timestamp']

107900

In [270]:
# Generate array of dwells
dwells = []
if len(ht_starts) == 1:
    dwells.append(df_indiv.iloc[-1, 1] - df_indiv.loc[0, 'timestamp'])
else:
    for start, end in zip(ht_starts, ht_ends):
        start_time = df_indiv.iloc[start, 1]
        end_time = df_indiv.iloc[end, 1]
        dwells.append(end_time - start_time)
dwells = np.array(dwells)
dwells

array([1627, 3211, 4796, 3211,    0])

In [271]:
# Construct HT table for individual
df_HTs = df_indiv.iloc[ht_starts, :]
df_HTs['dwell'] = dwells / 1000.

cols_2 = ['person_index', 'timestamp', 'dwell']

df_HTs = df_HTs[cols_2]

cols_renamed = ['person_index', 'HT_start', 'HT_dwell']
df_HTs.columns = cols_renamed

df_HTs

person_index  HT_start  HT_dwell
0             46     15765     1.627
7             46     31990     3.211
23            46     54429     4.796
41            46     73031     3.211
56            46    123665     0.000

In [ ]:
# next steps: 
# Filter by yaw
# Iterate this through each individual
#     Filter for dwell minimum
# append dataframes
# sort by HT start
# reindex
# Calculate stats: HT counts, HT distinct viewers, HTR
# put into a function