In [1]:
import numpy as np
import pandas as pd

from sqlalchemy import create_engine
from sqlalchemy.types import VARCHAR, Integer, Float

In [2]:
connection_str = 'postgresql:///measureyes'
engine = create_engine(connection_str, echo=False)

In [37]:
target_vid = 'Measureyes_0924_01.mp4'

Query_raw = ("""
SELECT * 
FROM rekmaster 
WHERE video = '{}'
ORDER BY person_index, timestamp
;""".format(target_vid)
            )

In [38]:
# Import all records for video
all_recs = pd.read_sql_query(Query_raw, engine)

In [54]:
all_recs.iloc[25:35,]

video                            source_file  timestamp  \
25  Measureyes_0924_01.mp4  Measureyes_0924_01_response_0001.json       1251   
26  Measureyes_0924_01.mp4  Measureyes_0924_01_response_0001.json       1292   
27  Measureyes_0924_01.mp4  Measureyes_0924_01_response_0001.json       1376   
28  Measureyes_0924_01.mp4  Measureyes_0924_01_response_0001.json       1459   
29  Measureyes_0924_01.mp4  Measureyes_0924_01_response_0001.json       1501   
30  Measureyes_0924_01.mp4  Measureyes_0924_01_response_0001.json          0   
31  Measureyes_0924_01.mp4  Measureyes_0924_01_response_0001.json         41   
32  Measureyes_0924_01.mp4  Measureyes_0924_01_response_0001.json        125   
33  Measureyes_0924_01.mp4  Measureyes_0924_01_response_0001.json        166   
34  Measureyes_0924_01.mp4  Measureyes_0924_01_response_0001.json        250   

    person_index  face_yaw  face_pitch  face_box_top  face_box_left  
25             1       NaN         NaN           NaN            NaN  
26             1       NaN         NaN           NaN            NaN  
27             1       NaN         NaN           NaN            NaN  
28             1       NaN         NaN           NaN            NaN  
29             1       NaN         NaN           NaN            NaN  
30             2       NaN         NaN           NaN            NaN  
31             2       NaN         NaN           NaN            NaN  
32             2       NaN         NaN           NaN            NaN  
33             2       NaN         NaN           NaN            NaN  
34             2       NaN         NaN           NaN            NaN

In [56]:
# get the sample rate in milliseconds; it's timestamp at record idx 1
sample_rate = all_recs.loc[1, 'timestamp']
print("sample rate in milliseconds:", sample_rate)

sample rate in milliseconds: 41


In [132]:
# Get dataframe of only records where yaw was recorded
pose_recs = all_recs.dropna(subset=['face_yaw'])

cols = ['timestamp', 'person_index', 'face_yaw', 'face_pitch', 'face_box_top', 'face_box_left']
pose_recs = pose_recs[cols]

In [41]:
pose_recs.head(30)

timestamp  person_index   face_yaw  face_pitch  face_box_top  \
893       11386            19 -32.426006   -4.658849      0.340278   
2046       6172            31 -31.617493   -2.338707      0.372222   
2058       5797            32  -2.420268    0.076770      0.370833   
2059       6798            32 -14.524308   -2.389813      0.336111   
2061       8383            32 -60.660793  -12.552453      0.323611   
2066       9175            32 -44.529732   -2.461496      0.337500   
2072       9968            32 -43.117874    5.770154      0.298611   
2081      10760            32  45.096027    5.798729      0.225000   
2087      11177            32 -43.739269  -16.429325      0.334722   
2092      11594            32  28.041138    3.179321      0.306944   
2095      11761            32  37.007511    1.483932      0.313889   
2098      11970            32 -21.160686   -4.133566      0.320833   
2100      12178            32 -29.299463    2.243401      0.326389   
2106      13596            32 -53.104042   14.199553      0.290278   
2108      13972            32 -12.002819   -6.118839      0.330556   
2109      14180            32 -34.907864   -3.154411      0.333333   
2110      14597            32 -24.613615   -3.087893      0.297222   
2111      15181            32 -30.050991    3.117698      0.288889   
2115      17183            32  32.403137   -2.830890      0.331944   
2116      17559            32  35.116890   -1.129844      0.337500   
2117      19769            32 -25.723946    9.581967      0.400000   
2118      20186            32 -28.679161    6.580540      0.397222   
2120      24607            32 -37.713783    3.485850      0.294444   
2123      24774            32 -29.990259    7.390715      0.283333   
2126      24983            32 -33.441559   -3.994164      0.315278   
2148      27402            32   7.206143    2.051757      0.351389   
2150      27986            32   5.223285    4.985424      0.316667   
2153      28194            32   1.782915    6.459267      0.293056   
2156      28403            32   2.682993    3.395409      0.287500   
2159      28611            32   3.751116    1.174402      0.311111   

      face_box_left  
893        0.096094  
2046       0.798437  
2058       0.908594  
2059       0.225000  
2061       0.892187  
2066       0.667188  
2072       0.799219  
2081       0.867969  
2087       0.288281  
2092       0.831250  
2095       0.885938  
2098       0.052344  
2100      -0.005469  
2106       0.758594  
2108       0.692187  
2109       0.625000  
2110       0.799219  
2111       0.549219  
2115      -0.005469  
2116       0.088281  
2117       0.939062  
2118       0.806250  
2120       0.885938  
2123       0.803125  
2126       0.689844  
2148       0.876562  
2150       0.927344  
2153       0.848437  
2156       0.750781  
2159       0.660937

In [45]:
print(pose_recs['person_index'].unique())
print(len(pose_recs['person_index'].unique()))

[ 19  31  32  33  34  36  37  38  43  46  47  53  57  58  61  62  63  67
  74 112 146 149 153 155 157 165]
26


In [81]:
# Eight most commonly spotted persons with yaws recorded
pd.value_counts(pose_recs['person_index'])[:8]

32     153
34     132
33      61
46      57
47      46
67      19
112      4
149      4
Name: person_index, dtype: int64

In [162]:
# Grab and re-index a dataframe of records from only one person_index
df_indiv = pose_recs[pose_recs['person_index'] == 47]
df_indiv.index = range(len(df_indiv))

In [163]:
df_indiv.tail(15)

timestamp  person_index   face_yaw  face_pitch  face_box_top  \
31     122288            47  -7.726277    8.708318      0.340278   
32     122497            47  -3.963156    4.806909      0.344444   
33     122664            47 -15.447542   12.107210      0.336111   
34     122872            47  -9.337505   12.930905      0.336111   
35     123081            47 -19.681353   10.007972      0.340278   
36     123289            47 -21.866674   12.696220      0.338889   
37     123498            47 -19.594091   14.004229      0.326389   
38     123665            47 -11.753841   14.979022      0.329167   
39     123873            47 -23.703493   17.788671      0.329167   
40     124082            47 -28.263613   15.712262      0.333333   
41     124499            47 -21.023357   12.686701      0.347222   
42     124666            47 -22.248541   10.932757      0.348611   
43     124874            47 -21.793829   11.730590      0.345833   
44     125083            47 -23.387943   11.114038      0.350000   
45     125291            47 -23.913055    6.268059      0.354167   

    face_box_left  
31       0.783594  
32       0.735156  
33       0.696875  
34       0.653906  
35       0.617969  
36       0.581250  
37       0.550781  
38       0.526563  
39       0.500000  
40       0.474219  
41       0.426562  
42       0.412500  
43       0.392969  
44       0.361719  
45       0.316406

In [164]:
# Turn off an annoying and irrelevant SettingWithCopy error: see https://stackoverflow.com/questions/42105859/pandas-map-to-a-new-column-settingwithcopywarning
pd.options.mode.chained_assignment = None

In [165]:
df_indiv['timediff'] = df_indiv['timestamp'].diff().fillna(0)

In [166]:
cols2 = ['person_index', 'timestamp', 'timediff', 'face_yaw']
df_indiv = df_indiv[cols2]
df_indiv.head(12)

person_index  timestamp  timediff   face_yaw
0             47      25775       0.0  48.906502
1             47      25984     209.0  22.720251
2             47      26192     208.0  33.048267
3             47      26401     209.0  31.400949
4             47      26776     375.0  45.446892
5             47      47005   20229.0  -4.905740
6             47      47422     417.0   1.781349
7             47      47589     167.0 -11.161950
8             47      47797     208.0   1.142745
9             47      48006     209.0   3.125486
10            47      48214     208.0   0.434869
11            47      48423     209.0 -12.625751

In [167]:
df_indiv[df_indiv['timediff'] >= 1500]

person_index  timestamp  timediff   face_yaw
5             47      47005   20229.0  -4.905740
27            47     121496   69695.0 -17.933327

In [161]:
all_recs[all_recs['timestamp'].between(8250, 8383)]

video                            source_file  \
526   Measureyes_0924_01.mp4  Measureyes_0924_01_response_0002.json   
527   Measureyes_0924_01.mp4  Measureyes_0924_01_response_0002.json   
528   Measureyes_0924_01.mp4  Measureyes_0924_01_response_0002.json   
693   Measureyes_0924_01.mp4  Measureyes_0924_01_response_0002.json   
727   Measureyes_0924_01.mp4  Measureyes_0924_01_response_0002.json   
728   Measureyes_0924_01.mp4  Measureyes_0924_01_response_0002.json   
729   Measureyes_0924_01.mp4  Measureyes_0924_01_response_0002.json   
867   Measureyes_0924_01.mp4  Measureyes_0924_01_response_0002.json   
868   Measureyes_0924_01.mp4  Measureyes_0924_01_response_0002.json   
869   Measureyes_0924_01.mp4  Measureyes_0924_01_response_0002.json   
1940  Measureyes_0924_01.mp4  Measureyes_0924_01_response_0002.json   
1994  Measureyes_0924_01.mp4  Measureyes_0924_01_response_0002.json   
2060  Measureyes_0924_01.mp4  Measureyes_0924_01_response_0002.json   
2061  Measureyes_0924_01.mp4  Measureyes_0924_01_response_0002.json   
2740  Measureyes_0924_01.mp4  Measureyes_0924_01_response_0002.json   
2741  Measureyes_0924_01.mp4  Measureyes_0924_01_response_0002.json   
2742  Measureyes_0924_01.mp4  Measureyes_0924_01_response_0002.json   
3109  Measureyes_0924_01.mp4  Measureyes_0924_01_response_0002.json   
3110  Measureyes_0924_01.mp4  Measureyes_0924_01_response_0002.json   
3111  Measureyes_0924_01.mp4  Measureyes_0924_01_response_0002.json   
3746  Measureyes_0924_01.mp4  Measureyes_0924_01_response_0002.json   
3747  Measureyes_0924_01.mp4  Measureyes_0924_01_response_0002.json   

      timestamp  person_index   face_yaw  face_pitch  face_box_top  \
526        8258            11        NaN         NaN           NaN   
527        8299            11        NaN         NaN           NaN   
528        8383            11        NaN         NaN           NaN   
693        8258            15        NaN         NaN           NaN   
727        8258            16        NaN         NaN           NaN   
728        8299            16        NaN         NaN           NaN   
729        8383            16        NaN         NaN           NaN   
867        8258            19        NaN         NaN           NaN   
868        8299            19        NaN         NaN           NaN   
869        8383            19        NaN         NaN           NaN   
1940       8383            28        NaN         NaN           NaN   
1994       8383            30        NaN         NaN           NaN   
2060       8299            32        NaN         NaN           NaN   
2061       8383            32 -60.660793  -12.552453      0.323611   
2740       8258            33        NaN         NaN           NaN   
2741       8299            33        NaN         NaN           NaN   
2742       8383            33  23.224436    2.316713      0.300000   
3109       8258            34        NaN         NaN           NaN   
3110       8299            34        NaN         NaN           NaN   
3111       8383            34  77.314545   -6.842150      0.197222   
3746       8258            37        NaN         NaN           NaN   
3747       8299            37        NaN         NaN           NaN   

      face_box_left  
526             NaN  
527             NaN  
528             NaN  
693             NaN  
727             NaN  
728             NaN  
729             NaN  
867             NaN  
868             NaN  
869             NaN  
1940            NaN  
1994            NaN  
2060            NaN  
2061       0.892187  
2740            NaN  
2741            NaN  
2742       0.701563  
3109            NaN  
3110            NaN  
3111       0.299219  
3746            NaN  
3747            NaN

In [148]:
np.sort(df_indiv['timediff'].values)

array([   0.,  167.,  167.,  167.,  167.,  167.,  167.,  167.,  167.,
        167.,  167.,  167.,  167.,  167.,  167.,  167.,  167.,  167.,
        167.,  167.,  167.,  167.,  208.,  208.,  208.,  208.,  208.,
        208.,  208.,  208.,  208.,  208.,  208.,  208.,  208.,  208.,
        208.,  208.,  208.,  208.,  208.,  208.,  208.,  208.,  208.,
        208.,  208.,  208.,  209.,  209.,  209.,  209.,  209.,  209.,
        209.,  209.,  209.,  209.,  209.,  209.,  209.,  209.,  209.,
        209.,  209.,  209.,  209.,  209.,  209.,  209.,  209.,  209.,
        209.,  209.,  375.,  375.,  375.,  375.,  376.,  376.,  376.,
        417.,  417.,  417.,  417.,  417.,  417.,  417.,  417.,  417.,
        417.,  417.,  417.,  417.,  417.,  417.,  417.,  417.,  417.,
        584.,  584.,  584.,  584.,  584.,  584.,  584.,  584.,  626.,
        626.,  792.,  792.,  792.,  793.,  793.,  834.,  834.,  834.,
        834.,  834., 1001., 1001., 1001., 1001., 1001., 1168., 1209.,
       1210., 1210.,

In [87]:
prev_vals = q[:-1]
print(q[-3:], q[:3])
print(prev_vals[-3:], prev_vals[:3])

[127293 128294 128503] [5797 6798 8383]
[126709 127293 128294] [5797 6798 8383]


In [ ]:
prev_vals.put()

In [ ]:
def timedelta(df):
    """Add timedelta row to dataframe"""
    
    # create prev_value array